os:
  - linux
  - osx

sudo: false

script:
  - cd ..
  - pwd
  - ./binder/install-conda.sh
  - source binder/env.sh
  - conda list
  - python binder/imports.py
  - ./binder/install-texlive.sh
  - pdflatex --version


