name: malariagen
channels:
  - defaults
  - pyviz/label/dev
  - bokeh/label/dev
  - intake
  - bioconda
  - conda-forge
dependencies:
  - nomkl
  - python=3.6
  - bcftools=1.9
  - bcolz=1.2.1
  - biopython=1.73
  - bokeh=1.2.0
  - bqplot=0.11.6
  - cartopy=0.17.0
  - click=7.0
  - cython=0.29.12
  - cytoolz=0.10.0
  - dask=2.1.0
  - dask-kubernetes=0.9.0
  - dask-ml=1.0.0
  - distributed=2.1.0
  - fastcluster=1.1.25
  - fastparquet=0.3.1
  - fusepy=3.0.1
  - gcsfs=0.2.3
  - graphviz=2.40.1
  - h5py=2.9.0
  - hmmlearn=0.2.1
  - holoviews=1.12.3
  - htslib=1.9
  - humanize=0.5.1
  - intake-xarray=0.3.0
  - intervaltree=3.0.2
  - ipykernel=5.1.1
  - ipython=7.6.1
  # disable for now, not compatible with xarray 0.11.0
  # - ipyleaflet=0.9.2
  - ipywidgets=7.5.0
  - jedi=0.14.1
  - joblib=0.13.2
  - jupyter=1.0.0
  - jupyter_console=6.0.0
  - jupyter_client=5.3.1
  # N.B. jupyterhub versions need to match hub image
  # https://repo2docker.readthedocs.io/en/latest/howto/jupyterhub_images.html
  - jupyterhub=1.0.0
  - jupyterlab=1.0.2
  - jupyterlab_launcher=0.13.1
  - jupytext=1.1.7
  - lmfit=0.9.13
  - matplotlib=3.1.1
  - matplotlib-venn=0.11.5
  - msgpack-python=0.6.1
  - msprime=0.7.1
  - mysqlclient=1.3.13
  - nb_conda_kernels=2.2.2
  - nbconvert=5.5.0
  - nbserverproxy=0.8.8
  - nodejs=11.14.0
  - nose=1.3.7
  - notebook=5.7.8
  - numba=0.44.1
  - numcodecs=0.6.3
  - numexpr=2.6.9
  - numpy=1.16.4
  - openpyxl=2.6.2
  - pandas=0.24.2
  - peakutils=1.3.2
  - petl=1.2.0
  - pillow=6.1.0
  - psutil=5.6.3
  - pyfasta=0.5.2
  - pyfaidx=0.5.5.2
  - pysam=0.15.2
  - pysamstats=1.1.2
  - pytables=3.5.2
  - python-blosc=1.8.1
  - python-graphviz=0.11.1
  - python-kubernetes=10.0.0
  - pyvcf=0.6.8
  - pyzmq=18.0.2
  - qtconsole=4.5.1
  - s3fs=0.2.2
  - samtools=1.9
  - scikit-allel=1.2.1
  - scikit-image=0.15.0
  - scikit-learn=0.21.2
  - scipy=1.3.0
  - seaborn=0.9.0
  - snakemake=5.4.0
  - toolz=0.10.0
  - tornado=6.0.3
  - xarray=0.12.3
  - xlrd=1.2.0
  - xlwt=1.3.0
  - zarr=2.3.2
  - zict=1.0.0
  - pip=19.1.1
  - pip:
    # not on conda-forge
    - cached_property==1.5.1
    # not on conda-forge
    - anhima==0.11.2
    # not on conda-forge
    - prettypandas==0.0.4
    # not build for Python 3.6 on conda-forge
    - petlx==1.0.3
    # not on conda-forge
    - scikits.bootstrap==1.0.0-pypi2
    # others
    - Sphinx==1.8.2
    - sphinx-autobuild==0.7.1
    - sphinx-bootstrap-theme==0.6.5
