name: malariagen
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - nomkl
  - python=3.6
  - bcftools=1.9
  - bcolz=1.2.1
  - biopython=1.72
  - cartopy=0.17.0
  - cython=0.29.2
  - cytoolz=0.9.0.1
  - dask=1.0.0
  - fastcluster=1.1.25
  - graphviz=2.40.1
  - h5py=2.8.0
  - hmmlearn=0.2.0
  - htslib=1.9
  - humanize=0.5.1
  - intervaltree=2.1.0
  - ipykernel=5.1.0
  - ipython=7.2.0
  - ipywidgets=7.4.2
  - joblib=0.13.0
  - jupyter_console=6.0.0
  - lmfit=0.9.11
  - matplotlib=3.0.2
  - matplotlib-venn=0.11.5
  - msprime=0.6.1
  - mysqlclient=1.3.14
  - nbconvert=5.4.0
  - nose=1.3.7
  - notebook=5.7.4
  - numcodecs=0.6.2
  - numexpr=2.6.8
  - numpy=1.15.4
  - openpyxl=2.5.12
  - pandas=0.23.4
  - peakutils=1.3.0
  - petl=1.2.0
  - pillow=5.3.0
  - psutil=5.4.8
  - pyfasta=0.5.2
  - pyfaidx=0.5.5.2
  - pytables=3.4.4
  - pyvcf=0.6.8
  - qtconsole=4.4.3
  - samtools=1.9
  - scikit-allel=1.1.10
  - scikit-learn=0.19.2
  - scipy=1.1.0
  - seaborn=0.9.0
  - snakemake=5.3.1
  - toolz=0.9.0
  - xlrd=1.2.0
  - xlwt=1.3.0
  - zarr=2.2.0
  - pip:
    # version discrepancy for pysam on bioconda, install from pypi to be sure
    - pysam==0.15.1
    - pysamstats==1.1.2
    # not on conda-forge
    - anhima==0.11.2
    # not on conda-forge
    - prettypandas==0.0.4
    # version not on conda-forge
    - graphviz==0.10.1
    # not build for Python 3.6 on conda-forge
    - petlx==1.0.3
    # not on conda-forge
    - scikits.bootstrap==1.0.0-pypi2
    # others
    - Sphinx==1.8.2
    - sphinx-autobuild==0.7.1
    - sphinx-bootstrap-theme==0.6.5
