name: malariagen
channels:
  - defaults
  - pyviz/label/dev
  - bokeh/label/dev
  - intake
  - bioconda
  - conda-forge
dependencies:
  - nomkl
  - python=3.6
  - bcftools=1.9
  - bcolz=1.2.1
  - biopython=1.73
  - bokeh=1.0.4
  - bqplot=0.11.2
  - cartopy=0.17.0
  - cython=0.29.4
  - cytoolz=0.9.0.1
  - dask=1.1.1
  - dask-ml=0.11.0
  - distributed=1.25.3
  - fastcluster=1.1.25
  - fastparquet=0.2.1
  - gcsfs=0.2.0
  - graphviz=2.40.1
  - h5py=2.9.0
  - hmmlearn=0.2.1
  - holoviews=1.10.9
  - htslib=1.9
  - humanize=0.5.1
  - intake-xarray=0.2.4
  - intervaltree=3.0.2
  - ipykernel=5.1.0
  - ipython=7.2.0
  # disable for now, not compatible with xarray 0.11.0
  # - ipyleaflet=0.9.2
  - ipywidgets=7.4.2
  - joblib=0.13.1
  - jupyter=1.0.0
  - jupyter_console=6.0.0
  - jupyter_client=5.2.4
  # N.B. jupyterhub versions need to match hub image
  # https://repo2docker.readthedocs.io/en/latest/howto/jupyterhub_images.html
  - jupyterhub=0.9.4
  - jupyterlab=0.35.4
  - jupyterlab_launcher=0.13.1
  - jupytext=1.1.1
  - lmfit=0.9.12
  - matplotlib=3.0.2
  - matplotlib-venn=0.11.5
  - msgpack-python=0.6.1
  - msprime=0.6.2
  - mysqlclient=1.3.14
  - nb_conda_kernels=2.2.0
  - nbconvert=5.4.0
  - nodejs=11.9.0
  - nose=1.3.7
  - notebook=5.7.4
  - numba=0.41.0
  - numcodecs=0.6.3
  - numexpr=2.6.9
  - numpy=1.16.1
  - openpyxl=2.5.14
  - pandas=0.24.1
  - peakutils=1.3.2
  - petl=1.2.0
  - pillow=5.4.1
  - psutil=5.5.0
  - pyfasta=0.5.2
  - pyfaidx=0.5.5.2
  - pysam=0.15.2
  - pysamstats=1.1.2
  - pytables=3.4.4
  - python-blosc=1.7.0
  - pyvcf=0.6.8
  - pyzmq=17.1.2
  - qtconsole=4.4.3
  - s3fs=0.2.0
  - samtools=1.9
  - scikit-allel=1.2.0
  - scikit-image=0.14.2
  - scikit-learn=0.20.2
  - scipy=1.2.0
  - seaborn=0.9.0
  - snakemake=5.4.0
  - toolz=0.9.0
  - tornado=5.1.1
  - xarray=0.11.3
  - xlrd=1.2.0
  - xlwt=1.3.0
  - zarr=2.3.1
  - zict=0.1.3
  - pip=19.1
  - pip:
    # not on conda-forge
    - anhima==0.11.2
    # not on conda-forge
    - prettypandas==0.0.4
    # version not on conda-forge
    - graphviz==0.10.1
    # not build for Python 3.6 on conda-forge
    - petlx==1.0.3
    # not on conda-forge
    - scikits.bootstrap==1.0.0-pypi2
    # others
    - Sphinx==1.8.2
    - sphinx-autobuild==0.7.1
    - sphinx-bootstrap-theme==0.6.5
    # others from pangeo
    - fusepy==3.0.1
    - click==7.0
    - jedi==0.13.2
    - kubernetes==8.0.1
    - dask-kubernetes==0.7.0
    - nbserverproxy==0.8.8
