name: conda
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install conda and solve/verify conda environment
        run: |
          ./install-conda.sh
          source ./env.sh
          conda list
          python imports.py
      - uses: actions/upload-artifact@v2
        with:
          name: Upload pinned environments
          path: environment-pinned-*.yml
